export const POST_AGENDA_STORAGE_KEY = 'te-post-agenda'

export const postAgendaContent = {
  title: 'Antes de tu llamada — Trading Exponencial',
  banner: 'Instrucción obligatoria — no avances sin completar estos pasos',
  stepProgressPending: 'Paso 1 de 2 pendiente',
  stepProgressDone: 'Paso 2 de 2 completado',
  headlineBefore: 'Si no miras este video',
  headlineAccent: 'cancelar tu llamada.',
  kicker: 'Tu llamada no continúa sin este video.',
  pendingTitle: 'Tu llamada todavía no está confirmada',
  pendingBody: 'Para completar el proceso, mira el siguiente video hasta el final.',
  videoLabel: '▶ Video obligatorio',
  videoMeta: '~5 min · sin esto no hay llamada',
  playHint: 'Toca para reproducir',
  warningLead: 'Si no miras este video, cancelamos tu llamada.',
  warningRest: ' Te explico cómo trabajo, qué necesitas tener listo antes y qué esperar de la llamada. No es opcional.',
  stepDoneLabel: '✓ Completado',
  stepDoneText: 'Agendaste tu llamada',
  stepPendingLabel: '⏳ Pendiente',
  stepPendingText: 'Mira el video completo — sin esto, no hay llamada',
  demoBadge: 'Reserva de prueba — no es una llamada real',
  mainVideo: {
    src: '/assets/post-appointment/demo-main.mp4',
    poster: '/assets/post-appointment/poster-main.jpg',
    driveId: '1M1ZTnAdY_IkkNcfbDrFwmcRO225HXDO2',
  },
  faqVideosEyebrow: 'Antes de la llamada',
  faqVideosTitle: 'Dudas frecuentes.',
  faqVideosTitleAccent: 'En video.',
  faqVideosLead: 'Estas preguntas aparecen siempre al final de la llamada. Mira los videos y llega con todo claro.',
  faqVideos: [
    {
      id: 'faq-01',
      n: '01',
      title: '¿Necesito experiencia previa en trading?',
      poster: '/assets/post-appointment/faq-01.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
      driveId: '1u1U_rwaUSyUbzCuBLseWDiuOg5GM5bnn',
    },
    {
      id: 'faq-02',
      n: '02',
      title: '¿Cómo funciona el acompañamiento por dentro?',
      poster: '/assets/post-appointment/faq-02.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
      driveId: '1fIBcXJTIKX6zIAGSwdbtPZW5tRg0Cgog',
    },
    {
      id: 'faq-03',
      n: '03',
      title: '¿Cuándo empiezo a operar con resultados reales?',
      poster: '/assets/post-appointment/faq-03.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
      driveId: '1tzejxmYMaEqNSPWYvycDSwqH88FTLnCq',
    },
    {
      id: 'faq-04',
      n: '04',
      title: '¿Cuánto tiempo por día necesito dedicarle?',
      poster: '/assets/post-appointment/faq-04.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
      driveId: '1kZEMJ7P8HO8bNdJVRhJpymdcKysNhiuM',
    },
    {
      id: 'faq-05',
      n: '05',
      title: '¿Puedo escalar si empiezo con poco capital?',
      poster: '/assets/post-appointment/faq-05.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
      driveId: '1Ma6eG2FiQRO4IOBjh1bFuhnff5W4LOOv',
    },
    {
      id: 'faq-06',
      n: '06',
      title: '¿Esto es una señal de trading o me enseñan a operar solo?',
      poster: '/assets/post-appointment/faq-06.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
      driveId: '1vxTXgczxyyT6WvdJh1mgMvqSGOiIQ5sK',
    },
  ],
  resultsEyebrow: 'Resultados reales',
  resultsTitle: 'Alumnos que',
  resultsTitleAccent: 'ejecutaron el método',
  resultsLead: 'Situaciones distintas. Mismo sistema. Resultados concretos.',
  stats: [
    { kicker: 'Sebastián · desde cero', value: '$1000', label: 'Su primer retiro en trading', highlight: false },
    { kicker: 'Alumnos · 1 hora al día', value: '1H', label: 'Tiempo diario de ejecución', highlight: false },
    { kicker: 'Método · sin señales', value: '100%', label: 'Sistema propio y reglas claras', highlight: false },
    { kicker: 'Acompañamiento · 1:1', value: '24/7', label: 'Discord, en vivo y chat privado', highlight: true },
  ],
  stories: [
    {
      name: 'Sebas',
      before: 'De 0 a retiros consistentes',
      accent: ' en su cuenta',
      after: '',
      text: 'Empezó sin experiencia previa y con capital mínimo. Siguió el sistema y las reglas de gestión de riesgo hasta escalar su cuenta.',
      kind: 'video' as const,
      poster: '/assets/post-appointment/sebas-poster.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
    },
    {
      name: 'Hector',
      before: 'Consistencia con ',
      accent: 'reglas claras',
      after: '',
      text: 'Ya operaba, pero sin sistema ni gestión de riesgo. Ordenó su ejecución y dejó de improvisar entradas y salidas.',
      kind: 'video' as const,
      poster: '/assets/post-appointment/hector-poster.jpg',
      src: '/assets/post-appointment/demo-main.mp4',
    },
    {
      name: 'Ana',
      before: 'Retiros ',
      accent: 'más grandes',
      after: ' y consistentes',
      text: 'Ya estaba retirando, pero sin poder escalar. Ajustamos varias cosas para crecer sin romper el riesgo y en 2 meses de la mentoría lleva +$20.000 en retiros.',
      kind: 'image' as const,
      poster: '/assets/post-appointment/ana-payouts.png',
    },
    {
      name: 'Jonas',
      before: 'Opera en ',
      accent: '1 hora',
      after: ' al día',
      text: 'Opera desde el trabajo y necesitaba un sistema que se ejecute en poco tiempo, sin estar pegado a la pantalla todo el día.',
      kind: 'image' as const,
      poster: '/assets/post-appointment/jonas-trade.png',
    },
  ],
  methodEyebrow: 'El método',
  methodTitle: 'Cómo trabajamos',
  methodTitleAccent: 'según tu perfil',
  methodLead: 'El acompañamiento se adapta a tu situación. No hay un solo camino — hay el tuyo.',
  profiles: [
    {
      n: '01',
      title: 'Trader desde cero',
      text: 'Nunca operaste y querés aprender un sistema simple y comprobado, sin perder tiempo en prueba y error.',
      highlight: true,
    },
    {
      n: '02',
      title: 'Trader con experiencia',
      text: 'Ya operas pero sin consistencia. Necesitas un sistema y gestión de riesgo real.',
      highlight: false,
    },
    {
      n: '03',
      title: 'Trader que busca crecer',
      text: 'Ya estás haciendo retiros, pero quieres escalar aún más y lograr retiros más grandes y consistentes.',
      highlight: false,
    },
    {
      n: '04',
      title: 'Profesional con poco tiempo',
      text: 'Trabajas full-time y quieres operar en 1-2 horas al día, sin estar pegado a la pantalla.',
      highlight: false,
    },
  ],
  faqEyebrow: 'Preguntas frecuentes',
  faqTitle: 'Lo que más',
  faqTitleAccent: 'preguntan',
  faqTitleAfter: ' antes de entrar',
  faqLead: 'Respuestas directas. Sin vueltas.',
  faqs: [
    {
      q: 'Nunca hice trading, ¿puedo empezar igual?',
      before: 'Sí. ',
      strong: 'El sistema está diseñado para arrancar desde cero',
      after: ', sin experiencia previa.',
    },
    {
      q: '¿Necesito mucho capital para empezar?',
      before: 'No. Puedes empezar con poco capital y escalar a medida que ganás consistencia.',
      proof: 'Gisell empezó con $75 en su cuenta y la llevó a $500.',
    },
    {
      q: '¿Cuánto tiempo por día tengo que dedicarle?',
      before: 'Con ',
      strong: '1 hora al día',
      after: ' es suficiente para operar el sistema completo.',
    },
    {
      q: '¿Esto es suerte o es un sistema real?',
      before: 'Es un sistema con ',
      strong: 'reglas claras de entrada, salida y gestión de riesgo',
      after: '. No es apuesta ni señales sin criterio.',
    },
    {
      q: '¿Qué pasa si pierdo dinero?',
      before: 'El trading conlleva riesgo real de pérdida de capital. Te enseño gestión de riesgo para operar de forma responsable.',
    },
    {
      q: '¿Por qué esto y no otro curso de trading?',
      before: 'Porque no necesitas otro curso más. Necesitas un ',
      strong: 'sistema claro',
      after: ', acompañamiento real y un proceso que te permita convertir conocimiento en resultados consistentes.',
    },
  ],
  footerBrand: 'Trading Exponencial',
  footerCopy: '© 2025 Trading Exponencial — Todos los derechos reservados',
}
